import type { Metadata } from "next";
import { Inter, Dancing_Script } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });
const ds = Dancing_Script({ subsets: ["latin"],
  weight: "400",
  variable: "--font-ds",
 });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} ${ds.variable}`}>
          <Script id="tawk" strategy="lazyOnload">
            {`
            var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
            (function(){
            var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
            s1.async=true;
            s1.src='https://embed.tawk.to/6621ccd1a0c6737bd12ddffa/1hrq0g506';
            s1.charset='UTF-8';
            s1.setAttribute('crossorigin','*');
            s0.parentNode.insertBefore(s1,s0);
            })();
        `}
          </Script>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
